# Generated by Django 5.2.1 on 2025-05-29 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Цвет цвета',
                'verbose_name_plural': 'Цвета цветов',
            },
        ),
        migrations.CreateModel(
            name='FlowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Типы цветов',
                'verbose_name_plural': 'Типы цветов',
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.flowercolour')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.flowertype')),
            ],
            options={
                'verbose_name': 'Цветок',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='OrderedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('city', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('building', models.CharField(max_length=512)),
                ('corpus', models.IntegerField()),
                ('flat', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
                ('time', models.CharField(max_length=128)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('flower_colour', models.ManyToManyField(related_name='chosen_flower_colour', to='app.flowercolour')),
                ('flower_type', models.ManyToManyField(related_name='chosen_flower_types', to='app.flowertype')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='ChosenFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('фуу...', 'фуу...'), ('нее', 'нее'), ('хз', 'хз'), ('норм', 'норм'), ('ваау!!', 'ваау!!')], max_length=56)),
                ('flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='app.flower')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_flowers', to='app.orderedby')),
            ],
            options={
                'verbose_name': 'Выбранные цветы',
                'verbose_name_plural': '\tВыбранные цветы',
            },
        ),
        migrations.CreateModel(
            name='ApprovedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('building', models.CharField(max_length=512)),
                ('corpus', models.IntegerField()),
                ('flat', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
                ('time', models.CharField(max_length=128)),
                ('is_address_typed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderedby')),
            ],
            options={
                'verbose_name': 'Утвердивший',
                'verbose_name_plural': 'Утвердившие',
            },
        ),
    ]
