# Generated by Django 5.2.1 on 2025-05-28 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chosenflower',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_flowers', to='app.data'),
        ),
        migrations.AlterField(
            model_name='chosenflower',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flowers', to='app.flower'),
        ),
    ]
