# Generated by Django 5.2.1 on 2025-05-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedby',
            name='name',
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='corpus',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='flat',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='phone_number',
            field=models.CharField(max_length=512),
        ),
    ]
