# Generated by Django 5.2.1 on 2025-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_approvedby_name_alter_orderedby_corpus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedby',
            name='corpus',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='flat',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
