# Generated by Django 5.2.1 on 2025-06-04 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_approvedby_corpus_alter_approvedby_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedby',
            name='building',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='corpus',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='flat',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='flower_colour',
            field=models.ManyToManyField(related_name='chosen_flower_colour', to='app.flowercolour', verbose_name='Цвет цветка'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='flower_type',
            field=models.ManyToManyField(related_name='chosen_flower_types', to='app.flowertype', verbose_name='Тип цветка'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='is_anonymous',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Анонимный'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='phone_number',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='street',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='time',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='visits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Посещения'),
        ),
    ]
