# Generated by Django 5.2.1 on 2025-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_orderedby_building_alter_orderedby_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedby',
            name='address_mentioned',
            field=models.BooleanField(default=True),
        ),
    ]
