# Generated by Django 5.2.1 on 2025-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orderedby_address_mentioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedby',
            name='order',
        ),
        migrations.AddField(
            model_name='approvedby',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
