# Generated by Django 5.2.1 on 2025-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_approvedby_order_approvedby_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedby',
            name='buyer_phone',
            field=models.CharField(null=True, verbose_name='Номер телефона покупателя'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='building',
            field=models.CharField(max_length=512, verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='city',
            field=models.CharField(max_length=512, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='corpus',
            field=models.CharField(verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='flat',
            field=models.CharField(verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='is_address_typed',
            field=models.BooleanField(default=False, verbose_name='Адрес написан?'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='phone_number',
            field=models.CharField(verbose_name='Номер телефона заказчика'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='street',
            field=models.CharField(max_length=512, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='time',
            field=models.CharField(max_length=128, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='uuid',
            field=models.UUIDField(verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderedby',
            name='address_mentioned',
            field=models.BooleanField(default=True, verbose_name='Адрес написан?'),
        ),
    ]
