# Generated by Django 5.2.1 on 2025-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_approvedby_buyer_phone_alter_approvedby_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedby',
            name='building',
            field=models.CharField(max_length=512, null=True, verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='city',
            field=models.CharField(max_length=512, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='corpus',
            field=models.CharField(null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='flat',
            field=models.CharField(null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='phone_number',
            field=models.CharField(null=True, verbose_name='Номер телефона заказчика'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='street',
            field=models.CharField(max_length=512, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='approvedby',
            name='time',
            field=models.CharField(max_length=128, null=True, verbose_name='Время'),
        ),
    ]
