# Generated by Django 5.2.1 on 2025-06-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_approvedby_building_alter_approvedby_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedby',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
